apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Configuration
metadata:
  name: configuration-aws-icp
  annotations:
    meta.crossplane.io/maintainer: darkmuggle
    meta.crossplane.io/description: "Middling Evil, Inc"
spec:
  crossplane:
    version: ">=v1.7.0-0"
  dependsOn:
    - configuration: xpkg.upbound.io/upbound/configuration-rds
      version: ">=v0.0.1"
    - configuration: xpkg.upbound.io/upbound/configuration-eks
      version: ">=v0.0.2"
